# Target
IF(CMAKE_SIZEOF_VOID_P EQUAL 8)
	SET(PLATFORM_TARGET x64)
	SET(TARGET_64 TRUE)
ELSEIF(CMAKE_SIZEOF_VOID_P EQUAL 4)
	SET(PLATFORM_TARGET x86)
ENDIF()

# Suffix
IF(TARGET_64)
    SET(LIB_DEBUG_SUFFIX "_64d")
    SET(LIB_RELEASE_SUFFIX "_64")
ELSE()
    SET(LIB_DEBUG_SUFFIX "_d")
    SET(LIB_RELEASE_SUFFIX "")
ENDIF()

# CompileFlags
ADD_DEFINITIONS(-DUNICODE -D_UNICODE)
IF(MSVC)
	SET(CMAKE_CXX_FLAGS "/DWIN32 /D_WINDOWS /W3 /WX /GR /EHsc /Zi /Wv:14")
	SET(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} /fp:fast /Ob2")
    
    SET(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS} /DEBUG")
	SET(CMAKE_STATIC_LINKER_FLAGS_RELEASE "${CMAKE_STATIC_LINKER_FLAGS_RELEASE} /DEBUG")
	SET(CMAKE_SHARED_LINKER_FLAGS_RELEASE "${CMAKE_SHARED_LINKER_FLAGS_RELEASE} /DEBUG")
	SET(CMAKE_MODULE_LINKER_FLAGS_RELEASE "${CMAKE_MODULE_LINKER_FLAGS_RELEASE} /DEBUG")
ENDIF()

SET(BUILD_CONFIG "$<$<CONFIG:Debug>:Debug>$<$<CONFIG:Release>:Release>")